service: todo-list-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    TODOS_TABLE: ${self:service}-${self:provider.stage}
  
functions:
  createTodo:
    handler: src/functions/createTodo.handler
    events:
      - http:
          path: todos
          method: post
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt TodosTable.Arn

  listTodos:
    handler: src/functions/listTodos.handler
    events:
      - http:
          path: todos
          method: get
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: !GetAtt TodosTable.Arn

  getTodo:
    handler: src/functions/getTodo.handler
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: !GetAtt TodosTable.Arn

  updateTodo:
    handler: src/functions/updateTodo.handler
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt TodosTable.Arn

  deleteTodo:
    handler: src/functions/deleteTodo.handler
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: !GetAtt TodosTable.Arn

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-iam-roles-per-function